=== Melia-Ferreira/Filmographie/TP1 - Exercice 2/FilmsSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="films" type="filmsType" />

<xs:complexType name="filmsType">
    <xs:sequence>
        <xs:element name = "film" type="filmType" 
        minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="acteurDescription" type="acteurDescriptionType" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="filmType">
    <xs:sequence>
        <xs:element name = "titre" type="xs:string" />
        <xs:element name = "exploitation" type="exploitationType" />
        <xs:element name = "acteurs" type="acteursType" />
        <xs:element name = "realisateur" type="xs:string" />
        <xs:element name = "genres" type="genresType" />
        <xs:element name = "duree" type="dureeType" />
        <xs:element name = "scenario" type="scenarioType" />
        <xs:element name = "image" type="imageType" />
    </xs:sequence>
    <xs:attribute name="annee" type="xs:gYear" />
    <xs:attribute name = "visa" type = "xs:positiveInteger" />
</xs:complexType>

<xs:complexType name="exploitationType">
    <xs:sequence>
        <xs:element name = "dateSortie" type="xs:string" />
        <xs:element name = "nbrEntree" type="xs:string" />
        <xs:element name = "nbrSalle" type="xs:string" />
        <xs:element name = "listepays" type="listepaysType" />
    </xs:sequence>
</xs:complexType>

    <xs:complexType name="listepaysType">
        <xs:sequence>
            <xs:element name = "pays" type="paysType"
                        minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="paysType"> <!-- simpleType car énumération -->
    <xs:restriction base="xs:string">
        <xs:enumeration value="Albanie"/>
        <xs:enumeration value="Allemagne"/>
        <xs:enumeration value="Andorre"/>
        <xs:enumeration value="Arménie"/>
        <xs:enumeration value="Autriche"/>
        <xs:enumeration value="Azerbaïdjan"/>
        <xs:enumeration value="Belgique"/>
        <xs:enumeration value="Biélorussie"/>
        <xs:enumeration value="Bosnie-Herzégovine"/>
        <xs:enumeration value="Bulgarie"/>
        <xs:enumeration value="Chypre"/>
        <xs:enumeration value="Croatie"/>
        <xs:enumeration value="Danemark"/>
        <xs:enumeration value="Espagne"/>
        <xs:enumeration value="Estonie"/>
        <xs:enumeration value="Finlande"/>
        <xs:enumeration value="France"/>
        <xs:enumeration value="Géorgie"/>
        <xs:enumeration value="Grèce"/>
        <xs:enumeration value="Hongrie"/>
        <xs:enumeration value="Irlande"/>
        <xs:enumeration value="Islande"/>
        <xs:enumeration value="Italie"/>
        <xs:enumeration value="Kosovo"/>
        <xs:enumeration value="Lettonie"/>
        <xs:enumeration value="Liechtenstein"/>
        <xs:enumeration value="Lituanie"/>
        <xs:enumeration value="Luxembourg"/>
        <xs:enumeration value="Macédoine du Nord"/>
        <xs:enumeration value="Malte"/>
        <xs:enumeration value="Moldavie"/>
        <xs:enumeration value="Monaco"/>
        <xs:enumeration value="Monténégro"/>
        <xs:enumeration value="Norvège"/>
        <xs:enumeration value="Pays-Bas"/>
        <xs:enumeration value="Pologne"/>
        <xs:enumeration value="Portugal"/>
        <xs:enumeration value="République tchèque"/>
        <xs:enumeration value="Roumanie"/>
        <xs:enumeration value="Royaume-Uni"/>
        <xs:enumeration value="Russie"/>
        <xs:enumeration value="Saint-Martin"/>
        <xs:enumeration value="Serbie"/>
        <xs:enumeration value="Slovaquie"/>
        <xs:enumeration value="Slovénie"/>
        <xs:enumeration value="Suède"/>
        <xs:enumeration value="Suisse"/>
        <xs:enumeration value="Turquie"/>
        <xs:enumeration value="Ukraine"/>
        <xs:enumeration value="Vatican"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="acteursType">
    <xs:sequence>
        <xs:element name = "acteur" type="acteurType"
                    minOccurs="1" maxOccurs="unbounded" >

            <xs:key name="idActeur">
                <xs:selector xpath="acteurDescription"/>
                <xs:field xpath="@id" />
            </xs:key>

        <xs:keyref name="refActeur" refer="idActeur">
            <xs:selector xpath="film/acteurs/acteur" />
            <xs:field xpath="@ref" />
        </xs:keyref>
        </xs:element>
    </xs:sequence>
</xs:complexType>

    <xs:complexType name="acteurType">
        <xs:attribute name = "ref" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="genresType">
        <xs:sequence>
            <xs:element name = "genre" type="genreType"
                        minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

<xs:simpleType name="genreType"> <!-- simpleType car énumération -->
    <xs:restriction base="xs:string">
            <xs:enumeration value="aventure"/>
            <xs:enumeration value="science-fiction"/>
            <xs:enumeration value="fantastique"/>
            <xs:enumeration value="action"/>
            <xs:enumeration value="thriller"/>
            <xs:enumeration value="drame"/>
            <xs:enumeration value="comédie"/>
            <xs:enumeration value="policier"/>
            <xs:enumeration value="guerre"/>
            <xs:enumeration value="western"/>
            <xs:enumeration value="historique"/>
            <xs:enumeration value="biographie"/>
            <xs:enumeration value="musical"/>
            <xs:enumeration value="romance"/>
            <xs:enumeration value="horreur"/>
            <xs:enumeration value="documentaire"/>
            <xs:enumeration value="animation"/>
            <xs:enumeration value="comédie dramatique"/>
            <xs:enumeration value="comédie musicale"/>
            <xs:enumeration value="comédie romantique"/>
            <xs:enumeration value="crime"/>
            <xs:enumeration value="érotique"/>
            <xs:enumeration value="espionnage"/>
            <xs:enumeration value="suspense"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="dureeType">
    <xs:attribute name = "temps" type="xs:positiveInteger" />
    <xs:attribute name = "unite" type="xs:string" default="min" />
</xs:complexType>

    <xs:complexType name="scenarioType" mixed="true">
        <xs:sequence>
            <xs:element name = "keyword" type="xs:string" />
            <xs:element name = "ev" type="evType" />
            <xs:element name = "personnage" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="evType" mixed="true">
        <xs:sequence>
            <xs:element name = "keyword" type="xs:string" />
            <xs:element name = "personnage" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="imageType">
        <xs:attribute name = "ref" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="acteurDescriptionType">
        <xs:sequence>
            <xs:element name = "nom" type="xs:string" />
            <xs:element name = "prenom" type="exploitationType" />
            <xs:element name = "dateNaissance" type="xs:date" />
            <xs:element name = "sexe" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="lieuNaissance" type="xs:string" />
    </xs:complexType>


</xs:schema>

=== Melia-Ferreira/Filmographie/TP1 - Exercice 2/filmographie.xml
<!DOCTYPE films SYSTEM "filmographie.dtd">
            
<films
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FilmsSchema.xsd">
    <film annee="2011" visa="114089">
        <titre>King kong</titre>
        <exploitation>
            <dateSortie>Mercredi 14 décembre 2011</dateSortie>
            <nbrEntree>2838759</nbrEntree>
            <nbrSalle>547</nbrSalle>
            <listepays>
                <pays>Italie</pays>
                <pays>Espagne</pays>
                <pays>Royaume-Uni</pays>
                <pays>Allemagne</pays>
            </listepays>
        </exploitation>
        <acteurs>
            <acteur ref ="1">Peter Jackson</acteur>
            <acteur ref ="2">Naomi Watts</acteur>
            <acteur ref ="3">Jack Black</acteur>
            <acteur ref ="4">Adrien Brody</acteur>
        </acteurs>
        <realisateur>Peter Jackson</realisateur>
        <genres>
            <genre>aventure</genre>
        </genres>
        <duree temps="188" unite="min"/>
        <scenario>New York, 1933. Artiste de music-hall à la rue, <personnage>Ann Darrow</personnage> rencontre l'audacieux
            <keyword>explorateur</keyword>/réalisateur <personnage>Carl Denham</personnage>. <ev>Ce dernier rêve de terminer son lm inachevé, mais nourrit
            surtout la folle ambition d'être le premier à découvrir le secret de la mystérieuse Skull Island.</ev> Il va
            entraîner <personnage>Ann</personnage> dans sa périlleuse <keyword>aventure</keyword>...
        </scenario>
        <image ref="KingKong.jpg"/>
    </film>
    <film annee="1994" visa="114089">
        <titre>Le roi lion</titre>
        <exploitation>
            <dateSortie>Mercredi 23 novembre 1994</dateSortie>
            <nbrEntree>7895984</nbrEntree>
            <nbrSalle>612</nbrSalle>
            <listepays>
                <pays>Portugal</pays>
                <pays>Allemagne</pays>
                <pays>Espagne</pays>
                <pays>Royaume-Uni</pays>
            </listepays>
        </exploitation>
        <acteurs>
            <acteur ref ="5">Emmanuel Curtil</acteur>
            <acteur ref ="6">Matthew Broderick</acteur>
            <acteur ref ="7">Dimitri Rougeul</acteur>
        </acteurs>
        <realisateur>Roger Allens</realisateur>
        <genres>
            <genre>animation</genre>
            <genre>aventure</genre>
            <genre>comédie musicale</genre>
        </genres>
        <duree temps="89" unite="min"/>
        <scenario>Sur les Hautes terres d’<keyword>Afrique</keyword> règne un <keyword>lion</keyword> tout-puissant, le roi <personnage>Mufasa</personnage>, que tous les hôtes de la
            jungle respectent et admirent pour sa sagesse et sa générosité. <ev> Son jeune fils <personnage>Simba</personnage> sait qu’un jour il lui succédera,
            conformément aux lois universelles du <keyword>cycle de la vie</keyword>, mais il est loin de deviner les épreuves et les sacrifices que lui
            imposera l’exercice du pouvoir.</ev> Espiègle, naïf et turbulent, le lionceau passe le plus clair de son temps à jouer avec sa
            petite copine <personnage>Nala</personnage> et à taquiner <personnage>Zazu</personnage>, son digne précepteur. Son futur <keyword>royaume</keyword> lui apparaît en songe comme un lieu enchanté
            où il fera bon vivre, s’amuser et donner des ordres. Cependant, l’univers de <personnage>Simba</personnage> n’est pas aussi sûr qu’il le croie.
            <personnage>Scar</personnage>, le frère de <personnage>Mufasa</personnage>, aspire en effet depuis toujours au trône. Maladivement jaloux de son aîné, il intrigue pour
            l’éliminer en même temps que son successeur. Misant sur la curiosité enfantine et le tempérament aventureux de Simba, 
            il révèle à celui-ci l’existence d’un mystérieux et dangereux cimetière d’éléphants. <personnage>Simba</personnage>, oubliant les avertissements
            répétés de son père, s’y rend aussitôt en secret avec Nala et se fait attaquer par 3 <keyword>hyènes</keyword> féroces. Par chance, <personnage>Mufasa</personnage>
            arrive à temps pour sauver l’imprudent lionceau et sa petite compagne. Mais <personnage>Scar</personnage> ne renonce pas à ses sinistres projets.
             Aidé des 3 hyènes, il attire <personnage>Simba</personnage> dans un ravin et lance à sa poursuite un troupeau de gnous. N’écoutant que son courage,
             <personnage>Mufasa</personnage> sauve à nouveau son fils et tente de se mettre à l’abri en gravissant la falaise. Repoussé par son frère félon,
             il périt sous les sabots des gnous affolés. <ev> <personnage>Scar</personnage> blâme alors l’innocent <personnage>Simba</personnage> pour la mort du Roi et le persuade de
             quitter pour toujours les Hautes terres. <personnage>Simba</personnage> se retrouve pour la première fois seul et démuni face à un monde hostile.
             C’est alors que le <keyword>destin</keyword> place sur sa route un curieux tandem d’amis... </ev>
        </scenario>
        <image ref="LeRoiLion.jpg"/>
    </film>
    <film annee="2023" visa="318196">
        <titre>Super Mario Bros, Le Film</titre>
        <exploitation>
            <dateSortie>Jeudi 5 avril 2023</dateSortie>
            <nbrEntree>5899305</nbrEntree>
            <nbrSalle>362</nbrSalle>
            <listepays>
                <pays>Portugal</pays>
                <pays>Allemagne</pays>
            </listepays>
        </exploitation>
        <acteurs>
            <acteur ref ="8">Pierre Tessier</acteur>
            <acteur ref ="9">Chris Pratt</acteur>
            <acteur ref ="10">Jérémie Covillault</acteur>
        </acteurs>
        <realisateur>Mathhew Fogel</realisateur>
        <genres>
            <genre>animation</genre>
            <genre>comédie</genre>
        </genres>
        <duree temps="92" unite="min"/>
        <scenario>Alors qu’ils tentent de réparer une canalisation souterraine, <ev><personnage>Mario</personnage> et son frère <personnage>Luigi</personnage>, tous deux <keyword>plombiers</keyword>,
             se retrouvent plongés dans un nouvel univers féerique à travers un mystérieux conduit.</ev> Mais lorsque les deux frères sont
             séparés, <personnage>Mario</personnage> s’engage dans une <keyword>aventure</keyword> trépidante pour retrouver <personnage>Luigi</personnage>.
           <ev>Dans sa quête, il peut compter sur l’aide du champignon <personnage>Toad</personnage>, habitant du Royaume Champignon, et les conseils avisés,
            en matière de techniques de <keyword>combat</keyword>, de la <personnage>Princesse Peach</personnage>, guerrière déterminée à la tête du <keyword>Royaume</keyword>. </ev> C’est ainsi que
            <personnage>Mario</personnage> réussit à mobiliser ses propres forces pour aller au bout de sa <keyword>mission</keyword>.
            </scenario>
        <image ref="SuperMarioBros.jpg"/>
    </film>
    <film annee="2006" visa="441620">
        <titre>Cars</titre>
        <exploitation>
            <dateSortie>Mercredi 14 juin 2006</dateSortie>
            <nbrEntree>380190</nbrEntree>
            <nbrSalle>3988</nbrSalle>
            <listepays>
                <pays>Autriche</pays>
                <pays>Belgique</pays>
                <pays>Royaume-Uni</pays>
            </listepays>
        </exploitation>
        <acteurs>
            <acteur ref ="11">Guillaume Canet</acteur>
            <acteur ref ="12">Owen Wilson</acteur>
            <acteur ref ="13">Bernard-Pierre Donnadieu</acteur>
        </acteurs>
        <realisateur>John Lasseter</realisateur>
        <genres>
            <genre>animation</genre>
            <genre>comédie</genre>
            <genre>action</genre>
            <genre>fantastique</genre>
        </genres>
        <duree temps="96" unite="min"/>
        <scenario><personnage>Flash McQueen</personnage>, une splendide <keyword>voiture</keyword> de course toute neuve promise au <keyword>succès</keyword>, découvre que dans la vie,
            ce n'est pas de franchir la ligne d'arrivée qui compte, mais le <keyword>parcours</keyword> que l'on a suivi. Parti pour participer à la
            prestigieuse Piston Cup, il atterrit suite à une déviation dans la petite ville tranquille de Radiator Springs, sur 
            la Route 66.
           <ev> <personnage>McQueen</personnage> va apprendre à connaître <personnage>Sally</personnage> (une élégante Porsche 2002), <personnage>Doc Hudson</personnage> (une Hudson Hornet 1951 au passé mystérieux),
             et <personnage>Mater</personnage> (une dépanneuse rouillée mais à qui on peut faire confiance). Ils vont l'aider à découvrir qu'il y a des choses
             plus importantes que les <keyword>trophées</keyword>, la <keyword>gloire</keyword> et les <keyword>sponsors</keyword>...</ev>
           </scenario>
        <image ref="Cars.jpg"/>
    </film>
    <acteurDescription id="1" lieuNaissance="Pukerua Bay">
        <nom>Jackson</nom>
        <prenom>Peter</prenom>
        <dateNaissance>31/10/1961</dateNaissance>
        <sexe>M</sexe>
    </acteurDescription>
    <acteurDescription id="2" lieuNaissance="Shoreham">
        <nom>Watts</nom>
        <prenom>Naomi</prenom>
        <dateNaissance>28/09/1968</dateNaissance>
        <sexe>F</sexe>
    </acteurDescription>
    <acteurDescription id="3" lieuNaissance="Hermosa Beach">
        <nom>Black</nom>
        <prenom>Jack</prenom>
        <dateNaissance>28/08/1969</dateNaissance>
        <sexe>M</sexe>
    </acteurDescription>
    <acteurDescription id="4" lieuNaissance="Woodhaven">
        <nom>Brody</nom>
        <prenom>Adrien</prenom>
        <dateNaissance>14/04/1973</dateNaissance>
        <sexe>M</sexe>
    </acteurDescription>
    <acteurDescription id="5" lieuNaissance="Charenton-le-Pont">
        <nom>Curtil</nom>
        <prenom>Emmanuel</prenom>
        <dateNaissance>07/02/1971</dateNaissance>
